name: " üóÑÔ∏è Local Cache"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  mirror:
    name: "Local Cache"
    runs-on: ubuntu-latest
    steps:
      - name: "üì•  Fetching Repository Contents"
        uses: actions/checkout@main
      - uses: varunsridharan/action-gitea-mirror@main
        name: "RUN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gh_username: ${{ secrets.GH_USERNAME }}
          gh_accesstoken: ${{ secrets.GH_TOKEN }}
          gitea_host: ${{ secrets.GITEA_HOST }}
          gitea_username: ${{ secrets.GITEA_USERNAME }}
          gitea_accesstoken: ${{ secrets.GITEA_TOKEN }}
          gistsSource: false
          localCache: true
          gistsStared: false
          repositoryStared: false
          repositorySource: false
          repositoryForked: false
